#! /bin/sh

set -e

update-alternatives --install /usr/bin/ctags ctags /usr/bin/ctags-universal 30 \
	--slave /usr/share/man/man1/ctags.1.gz ctags.1.gz /usr/share/man/man1/ctags-universal.1.gz
update-alternatives --install /usr/bin/etags etags /usr/bin/ctags-universal 10 \
	--slave /usr/share/man/man1/etags.1.gz etags.1.gz /usr/share/man/man1/ctags-universal.1.gz

#DEBHELPER#

exit 0
