#! /bin/sh

set -e

update-alternatives --install /usr/bin/ctags ctags /usr/bin/universal-ctags 30 \
	--slave /usr/share/man/man1/ctags.1.gz ctags.1.gz /usr/share/man/man1/universal-ctags.1.gz

#DEBHELPER#

exit 0
